services:
  api:
    build:
      context: ./backend/MyCityCouncil
      dockerfile: Dockerfile
    container_name: mycitycouncilproject-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JwtOptions__SecretKey=${JwtOptions__SecretKey}
      - JwtOptions__TokenExpiresHours=${JwtOptions__TokenExpiresHours}
      - JwtOptions__RefreshTokenExpiresHours=${JwtOptions__RefreshTokenExpiresHours}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: mycitycouncilproject-db
    environment:
      - POSTGRES_DB=mycitycouncil_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=28sql31
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge