// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCityCouncil.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyCityCouncil.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529204515_AddVotingInfoDetails")]
    partial class AddVotingInfoDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Committee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Committees_Name");

                    b.HasIndex("Specialization")
                        .HasDatabaseName("IX_Committees_Specialization");

                    b.ToTable("Committees", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.CommitteeInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsChairman")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CommitteesInfo_UserId");

                    b.HasIndex("CommitteeId", "DismissedAt")
                        .HasDatabaseName("IX_CommitteesInfo_CommitteeActiveStatus");

                    b.HasIndex("CommitteeId", "IsChairman")
                        .IsUnique()
                        .HasDatabaseName("IX_CommitteesInfo_OneActiveChairman")
                        .HasFilter("\"IsChairman\" = true AND \"DismissedAt\" IS NULL");

                    b.HasIndex("CommitteeId", "AppointedAt", "DismissedAt")
                        .HasDatabaseName("IX_CommitteesInfo_HistoryRange");

                    b.ToTable("CommitteesInfo", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommitteesInfo_DateRange", "\"DismissedAt\" IS NULL OR \"DismissedAt\" >= \"AppointedAt\"");
                        });
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Initiatives_Status");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "ApprovedAt")
                        .HasDatabaseName("IX_Initiatives_QueueSorting");

                    b.ToTable("Initiatives", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.PartiesInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("UserId", "DismissedAt")
                        .HasDatabaseName("IX_PartiesInfo_UserActiveStatus");

                    b.ToTable("PartiesInfo", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("Ideology")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Party", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("HeldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HeldAt")
                        .HasDatabaseName("IX_Sessions_HeldAt");

                    b.HasIndex("CommitteeId", "HeldAt")
                        .HasDatabaseName("IX_Sessions_CommitteeDate");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.SessionAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SessionId", "UserId")
                        .IsUnique();

                    b.ToTable("SessionAttendees", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotingInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotingInfoId", "VoterId")
                        .IsUnique();

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.VotingInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InitiativeAuthor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InitiativeCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiativeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("InitiativeTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsFinalized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("IsFinalized")
                        .HasDatabaseName("IX_VotingInfos_IsFinalized");

                    b.HasIndex("SessionId", "InitiativeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_VotingInfos_SessionInitiative");

                    b.ToTable("VotingInfos", (string)null);
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.CommitteeInfo", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.Committee", "Committee")
                        .WithMany("Memberships")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyCityCouncil.Domain.Models.User", "User")
                        .WithMany("CommitteesMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Committee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Initiative", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.PartiesInfo", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.Party", "Party")
                        .WithMany("Memberships")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyCityCouncil.Domain.Models.User", "User")
                        .WithMany("PartyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Session", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.Committee", "Committee")
                        .WithMany()
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.SessionAttendee", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.Session", "Session")
                        .WithMany("Attendees")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCityCouncil.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.User", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Vote", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.VotingInfo", "VotingInfo")
                        .WithMany("Votes")
                        .HasForeignKey("VotingInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VotingInfo");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.VotingInfo", b =>
                {
                    b.HasOne("MyCityCouncil.Domain.Models.Initiative", "Initiative")
                        .WithMany("VotingHistory")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyCityCouncil.Domain.Models.Session", "Session")
                        .WithMany("VotingResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Committee", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Initiative", b =>
                {
                    b.Navigation("VotingHistory");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Party", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.Session", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("VotingResults");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.User", b =>
                {
                    b.Navigation("CommitteesMemberships");

                    b.Navigation("PartyMemberships");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MyCityCouncil.Domain.Models.VotingInfo", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
